=== ponomaREG/4course2sem/Корпоративные сетевые технологии/ЛР/nope.dtd
<!ELEMENT film (DVD, BD)>
<!ELEMENT DVD (название, год, страна, режиссер)>
<!ELEMENT название (#PCDATA)>
<!ELEMENT страна (#PCDATA)>
<!ELEMENT режиссер (#PCDATA)>
<!ATTLIST DVD жанр CDATA #REQUIRED>
<!ATTLIST DVD год CDATA #REQUIRED>

=== ponomaREG/4course2sem/Корпоративные сетевые технологии/ЛР/~kokhanchikIrina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "nope.dtd">
<film>
  <DVD жанр="боевик">
    <название>Гладиатор</название>
    <год знач="2000"/>
    <страна>США, Великобритания</страна>
    <режиссер>Ридли Скотт</режиссер>
 </DVD>
<DVD жанр="драма">
    <название>Маленькие женщины</название>
    <год знач="2019"/>
    <страна>США</страна>
    <режиссер>Грета Гервиг</режиссер>
 </DVD>
<DVD жанр="криминал">
    <название>Джентльмены</название>
    <год знач="2019"/>
    <страна>США</страна>
    <режиссер>Гай Ричи</режиссер>
 </DVD>
<DVD жанр="биография">
    <название>Манк</название>
    <год знач="2020"/>
    <страна>США</страна>
    <режиссер>Девид Финчер</режиссер>
 </DVD>
<DVD жанр="военный">
    <название>1917</название>
    <год знач="2019"/>
    <страна>США</страна>
    <режиссер>Сэм Мендес</режиссер>
 </DVD>
<DVD жанр="драма">
    <название>Еще по одной</название>
    <год знач="2020"/>
    <страна>Дания</страна>
    <режиссер>Томас Винтерберг</режиссер>
 </DVD>
<DVD жанр="ужасы">
    <название>Маяк</название>
    <год знач="2019"/>
    <страна>США</страна>
    <режиссер>Роберт Эггерс</режиссер>
 </DVD>
</film>
